server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: notes-suite-backend
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/notes_suite
    username: notes_user
    password: notes_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
  
  cache:
    type: simple
    cache-names:
      - users
      - notes
      - tags
  
  security:
    user:
      name: admin
      password: admin

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 3600000  # 1 hour
  refresh-token-expiration: 604800000  # 7 days

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    display-operation-id: true
    show-extensions: true
    show-common-extensions: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# Logging Configuration
logging:
  level:
    com.notes: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.notes: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  flyway:
    enabled: false
  
  h2:
    console:
      enabled: true

logging:
  level:
    com.notes: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

---
# Docker Profile
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:postgresql://postgres:5432/notes_db
    username: notes_user
    password: notes_password

logging:
  level:
    com.notes: INFO
    org.springframework.security: WARN

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/notes_db}
    username: ${DATABASE_USERNAME:notes_user}
    password: ${DATABASE_PASSWORD:notes_password}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:5}
  
  flyway:
    enabled: true
    validate-on-migrate: true

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

springdoc:
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.notes: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  file:
    name: logs/notes-suite.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
